---
kind: pipeline
name: test
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: test
  image: python:3.8.2-alpine3.11
  resources:
    requests:
      cpu: 500
      memory: 100MiB
    limits:
      cpu: 500
      memory: 100MiB
  commands:
  - pip install pytest
  - apk add git
  - pip install -r requirements.txt
  - py.test

---

kind: pipeline
name: linux-arm
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1440
  resources:
    requests:
      cpu: 500
      memory: 100MiB
    limits:
      cpu: 500
      memory: 100MiB
  settings:
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

depends_on:
- test

---
kind: pipeline
name: linux-arm64
type: kubernetes

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: publish
  image: plugins/docker
  environment:
    PLUGIN_MTU: 1440
  resources:
    requests:
      cpu: 500
      memory: 100MiB
    limits:
      cpu: 500
      memory: 100MiB
  settings:
    repo: ${DRONE_REPO}
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm64

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

depends_on:
- test

---
kind: pipeline
name: manifests
type: kubernetes

platform:
  os: linux
  arch: arm

clone:
  depth: 1

steps:
- name: manifest
  pull: always
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: manifest.tmpl
    platforms:
    - linux/arm
    - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

node_selector:
  kubernetes.io/arch: arm

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*

depends_on:
- linux-arm
- linux-arm64

---
kind: secret
name: docker_username
get:
  path: drone-secrets
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: drone-secrets
  name: docker_password